name: tekartik_platform
version: 0.4.0
description: Get the global platform context
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  pub_semver: '>=2.0.0'
  collection: '>=1.15.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.9.3'

dev_dependencies:
  test: any
  dev_test: any
  build_runner: ">=0.8.8"
  build_test: ">=0.10.2"
  build_web_compilers: '>=0.4.0'
  process_run: '>=0.10.0+1'
