name: platform_repo_spport
description: Platform repo (tools)
version: 0.2.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.6.0

dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.0+2"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'
  path: ">=1.9.0"
  process_run: ">=1.2.1+1"
_dev_dependencies:
  # test dependencies without version
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      ref: dart3a
      path: platform_io
  tekartik_platform_browser:
    git:
      url: https://github.com/tekartik/platform.dart
      ref: dart3a
      path: platform_browser
  tekartik_platform_node:
    git:
      url: https://github.com/tekartik/platform.dart
      ref: dart3a
      path: platform_node
  tekartik_platform:
    git:
      url: https://github.com/tekartik/platform.dart
      ref: dart3a
      path: platform
resolution: workspace
